### ISSUE TITLE
Too many open connections error

### ISSUE THREAD

**Issue by wdxxs2z** [cloudfoundry/silk#4]
Hi:

  Recently, i meet an error:

  ENV: 6000+ apps and 10000+ instances, about 100+ cell node , 3 bbs

  then, i found some error in bbs node, such as:

![123](https://user-images.githubusercontent.com/5114510/40298646-63db0482-5d16-11e8-9d91-07aa17501dd8.jpg)

  and our mysql instance is 3 node, 3000 max conn.

**Comment by rosenhouse** [comment]
Have you tried configuring [`max_open_connections` property on the `silk-controller` job](https://bosh.io/jobs/silk-controller?source=github.com/cloudfoundry/silk-release&version=2.2.0#p%3dmax_open_connections)?

**Comment by wdxxs2z** [comment]
Hi @rosenhouse 

we use the default configuring: 0, and now we set the timeout value: 20 (previous the value is 5), then it seems to ease some time_wait.

This max_open_connections value should be set roughly how much appropriate?

**Comment by rosenhouse** [comment]
Maybe one per cell?

**Comment by wdxxs2z** [comment]
one per cell? what's mean?  Now we have 3 bbs instance, and use default value 0 with max_open_connections(pivotal cloud foundry)

**Comment by rosenhouse** [comment]
@rusha19 Did we have any guidance on this?   Any idea what we run on PWS?  I could see us saying "set it to the number of diego cells", or maybe just a fixed number (e.g. 20?).

cc @emalm in case you have context for BBS

**Comment by emalm** [comment]
The BBS defaults to a max open connections count of 200: https://github.com/cloudfoundry/bbs/blob/b05af81dd4171e7afab698fed9290279d0937d28/cmd/bbs/config/config.go#L86. I wouldn't recommend setting a max open conns value of 0, as in that case each DB client can potentially use an unbounded number of DB connections.

**Comment by wdxxs2z** [comment]
So, can we fix this default parameter setting in the next version of PCF?

In addition, there is another parameter: connect-timeout. In the current version of PCF, the value set is 5s, if we have a large back end data, whether the setting is reasonable?

**Comment by tylerschultz** [comment]
The addition of a default value was added in silk-release version 2.3.0.

We can see this version happens to be available in PCF 2.2.
