### ISSUE TITLE
I'd like to modify the silk-controllers database (mysql?)

### ISSUE THREAD

**Issue by rlewkowicz** [cloudfoundry/silk#5]
So I have a goal, which may be based on misconceptions. I'll ask my question and then perhaps someone will tell me why it's a bad idea, impossible, or I'm framing the idea wrong. 

I need to make a container guid routable from another container. 
Essentially c2c, but without internal domains. Example:

Guid 1: ff4c353a-afc4-4be0-7d4f-3aea
Guid 2: dca187f1-e36d-477e-7faf-0c91

From guid one: 

dca187f1-e36d-477e-7faf-0c91:~# ping ff4c353a-afc4-4be0-7d4f-3aea
ping: bad address 'ff4c353a-afc4-4be0-7d4f-3aea'

Now in my mind, if I'm able to modify the silk db, I can just add this guid and it will  be routable as is, without apps.internal. Docs say: 

silk-controller runs on at least one central node and manages IP subnet lease allocation across the cluster. It is implemented as a stateless HTTP JSON API backed by a SQL database.

So are there docs for this API? Can I just get to this db? Is there an endpoint I can poke at? I'm playing around on a diego_database instance and Idk what I'm really even looking for. 

Obviously, I'll run into a snag here and there probably as I get into network policies or just even general misconceptions, but I need a place to start breaking things so I can follow the trail to fix them. 

I have concepts in my mind for externally managing a small handful of guids I need routables. 

Anywho, I'm going to go start poking around the code, but It'd be cool beans if someone could give me a few pointers

**Comment by tylerschultz** [comment]
I'd be curious to know what is motivating you to shy away from using internal routes? What pain are you experiencing? There's a lot to this question and proposed solution, I'm wondering if we might be able to help you solution something different. The networking team can be reached in the cloudfoundry slack https://cloudfoundry.slack.com in the #networking channel. Come join us and tell us what problem you're trying to solve.

One thing that stands out to me as awkward with what you're toying with is that the silk db is about managing the overlay network and does not have information about apps or app containers. It's main purpose is to manage the subnet leases.

The information you're looking to store in the db more closely aligns with the policy-server in the cf-networking release: https://github.com/cloudfoundry/cf-networking-release/tree/develop/src/policy-server This api & db is all about permissions related to which set of containers is permitted to talk to another set of containers.

> So are there docs for this API? 
Perhaps the best documentation for the silk api is this integration test: https://github.com/cloudfoundry/silk/blob/master/controller/integration/integration_test.go

> Can I just get to this db? 
The bosh deployment manifest that corresponds to the silk-controller instance you are poking at contains all of the database credentials.

> Is there an endpoint I can poke at?
The endpoint is protected by mtls, so poking at it becomes a little cumbersome. Perhaps modifying tests would be easier way to iterate on what changes you'd like.

**Comment by rlewkowicz** [comment]
Thanks for the response @tylerschultz! 

I think I need an invite for https://cloudfoundry.slack.com (which I might be able to get through pivotal if I need)

I had dug around in the silk repo and noticed there was only a small number of endpoints. I'll have a look at the policy server. 

Ultimately, what we're trying to accomplish is probably better geared for something like swarm, but I'm bound by pseudo politics (for better or worse). We have this legacy system that was built before my time, and I'm tasked with migrating it. About 1100 applications (80% of which have been solved), but there's about 20% called batch apps that follow something similar to:

![image](https://user-images.githubusercontent.com/17415445/56509454-07ac2c80-64f5-11e9-9051-77ebeeadecd3.png)

In an ideal world, we'd just change some code, but one of my constraints is no code changes (if we can save x teams x man hours of code changes yada yada yada). So what we're doing is just taking all these old java apps, jamming them into a docker container, and putting them on CF vs writing them to be CF native. My plan for these apps to just have them add themselves to which ever series of needed assets 

![image](https://user-images.githubusercontent.com/17415445/56509616-7a1d0c80-64f5-11e9-9811-72c9eeb1ded3.png)

**Comment by moleske** [comment]
@rlewkowicz See https://slack.cloudfoundry.org/ for an invite. (Linked from https://www.cloudfoundry.org/community/)

**Comment by rosenhouse** [comment]
Sounds like you need both policy and service discovery (DNS resolution).

- To control policy between CF apps, you can use the `cf` CLI tool (look for `add-network-policy`) or [this REST API](https://github.com/cloudfoundry/cf-networking-release/blob/develop/docs/policy-server-external-api.md).

- For custom DNS responses, it's a bit more complex.  Can you restrict it to one instance per app?  If so, then you might be able to add `apps.internal` to [the `search_domains` list](https://github.com/cloudfoundry/cf-networking-release/blob/develop/jobs/garden-cni/spec#L32-L34) and then use 
   ```
   cf map-route appName apps.internal --hostname instanceGuid
   ```
  to set up internal DNS resolution for that instance.  But it only does what you want if there's exactly 1 instance per application.

Make sense?

**Comment by rlewkowicz** [comment]
@rosenhouse I think that makes it only accessible at instanceGuid.apps.internal? That was my original thought, but from in the container the code gets the pure hostname:

InetAddress.getLocalHost().getHostName();

This is what goes into the DB and without any code changes I need that hostname to be directly routable. I don't have a way to append .apps.internal

**Comment by rosenhouse** [comment]
@rlewkowicz I believe that the [DNS search domains](https://en.wikipedia.org/wiki/Search_domain) feature that I described above could help with that problem, no?

**Comment by rlewkowicz** [comment]
@rosenhouse search domains was the perfect solution! Wish I had spotted it. Thanks for the input!
