### ISSUE TITLE
Move this repo into a release

### ISSUE THREAD

**Issue by winkingturtle-vmw** [cloudfoundry/silk#52]
## Why
Silk was created so that it could be used outside of CF, go-import paths show that after the many years in production, [CF silk-release is the only user of this plugin](https://pkg.go.dev/code.cloudfoundry.org/silk).

**As a** user
**I want** merge silk code into silk-release (or preferred cf-networking-release see https://github.com/cloudfoundry/silk-release/issues/83)
**So that** we can simplify our pipeline and process without having to bump silk outside of the release and waiting long enough to bump within the silk-release. This will additionally remove concourse jobs that redundant (e.g bump-silk-in-silk-release)

## What
code.cloudfoundry.org/silk will be archived and will contain README redirecting anyone that will arrive at the repo to the preferred release instead.

## Acceptance Criteria
code.cloudfoundry.org/silk will no longer be used in our jobs.

**Comment by ameowlia** [comment]
I love this idea.

**Comment by jrussett** [comment]
This repo is ready to be archived and this issue is resolved.

This merged PR folded the `silk` src into `silk-release`: https://github.com/cloudfoundry/silk-release/pull/89
This merged PR adds a deprecation notice to `silk`: https://github.com/cloudfoundry/silk/pull/61
