### ISSUE TITLE
IPv6 Support?

### ISSUE THREAD

**Issue by mxplusb** [cloudfoundry/silk#6]
The cloud.gov team has compliance requirements to support IPv6 traffic from both government agencies as well as customers. We currently have limited support for IPv6 (incoming traffic only) and have run into internal platform issues due to supporting both IPv4 and IPv6. Are there plans to support both IPv4 and IPv6 within Silk?

**Comment by rosenhouse** [comment]
Hi @mxplusb, thanks for opening this issue.

We've considered IPv6 support in Silk for a while, but haven't yet got a clear sense from platform operations teams about what exactly they need.  This leaves us unable to decide amongst various options for implementation.

A few questions right off the bat:

1. Do you need Silk to work over an IPv6 infrastructure network, i.e. Diego cells have IPv6 addresses?
2. Do you need to send IPv6 traffic between application instances, i.e. inside the Silk overlay network?
3. Would you need app-to-app traffic to support both IPv4 and IPv6, or would it suffice to only support IPv6 in the overlay network?
4. Currently the Silk network is NAT'ed from the infrastructure network: i.e. traffic from outside the platform to the app container is DNATed at the Diego cell to a container IP, and traffic from an app container to an external destination is SNATed from the Diego cell IP.  If you answered Yes to questions 1 and 2, do you additionally require a single flat IPv6 network that connects containers and VMs?  Or would it suffice to retain the NATing between the networks?

Roughly speaking, these features are listed in order of cost-to-implement, with (4) being at least an order of magnitude more complex to deliver (assuming we do it in an infrastructure-agnostic way).

Thank you.

**Comment by mxplusb** [comment]
Sure, happy to answer.

> Do you need Silk to work over an IPv6 infrastructure network, i.e. Diego cells have IPv6 addresses?

Not a core requirement but definitely nice to have because then it's a unified dual stack network topology across the board. I think this would be more BOSH-specific than Silk, though.

> Do you need to send IPv6 traffic between application instances, i.e. inside the Silk overlay network?

This is the most important one. We've been bitten with this one fairly recently because customer traffic can originate with an IPv6 address, and if we leverage app proxying (app X is a proxy for app Y), sometimes we'll run into issues. We actually clarify in [our documentation](https://cloud.gov/docs/compliance/domain-standards/#ipv6) what the current limitations are to set expectations with our customers. We recommend leveraging internal domain names whenever possible for routing traffic between AIs, but that's not always followed. Having the ability to address a specific AI by IPv6 address would be helpful.

> Would you need app-to-app traffic to support both IPv4 and IPv6, or would it suffice to only support IPv6 in the overlay network?

Preferably both for compliance and operational reasons.

> Currently the Silk network is NAT'ed from the infrastructure network: i.e. traffic from outside the platform to the app container is DNATed at the Diego cell to a container IP, and traffic from an app container to an external destination is SNATed from the Diego cell IP. If you answered Yes to questions 1 and 2, do you additionally require a single flat IPv6 network that connects containers and VMs? Or would it suffice to retain the NATing between the networks?

I think the current NAT design pattern is fine, and having the same design pattern for both IPv6 and IPv4 is preferred (less operator overhead). It also helps from a compliance and auditing standpoint, if the IPv6 designs are the same as IPv4, that way we don't have to do more paperwork. I think the current NAT design pattern with IPv4 is also good because it demonstrates a clear delineation between the overlay network and the underlying network. That being said, any level of encapsulation which can provide the same NAT design construct (i.e. demonstrable network segmentation) would be fine, especially if the implementation cost is lower than NAT.

**Comment by rosenhouse** [comment]
Thank you I think I understand most of this.  

To dig in a bit more on one piece:

> This is the most important one. We've been bitten with this one fairly recently because customer traffic can originate with an IPv6 address, and if we leverage app proxying (app X is a proxy for app Y), sometimes we'll run into issues. We actually clarify in our documentation what the current limitations are to set expectations with our customers. We recommend leveraging internal domain names whenever possible for routing traffic between AIs, but that's not always followed. Having the ability to address a specific AI by IPv6 address would be helpful.


Ah, so this is about apps on the platform connecting to IPv6 destinations. 

You may even have a scenario where an app connects to another app via an external route, which may have an IPv6 address, e.g.

```
Frontend App --> backend.external.gov --> IPv6 address of platform load-balancer --> gorouter --> Backend App
```

So from the perspective of the Frontend app, it is connecting not to another app on the platform, but to an IPv6 address on the infrastructure network.

Am I understanding the scenario correctly?

So maybe there's a 5th question, which I didn't even think to ask about earlier:


5. Does an app on CF need to connect to a non-app network destination at an IPv6 address?  (That non-app network destination might be the IPv6 address of a platform load-balancer that ultimately proxies to another CF app, but the original network destination of the first TCP hop is IPv6)


Is *this* the core requirement?  If you had this, but app-to-app via Silk was still IPv4-only, would that meet your needs?  

(For what it's worth, this may be cheaper than any of the other features discussed above.)

**Comment by mxplusb** [comment]
> Am I understanding the scenario correctly?

For the most part, although I think I may have not described the scenarios well enough initially.

Here are the scenarios that we've been seeing:

```
# this works as intended
external request over IPv6 -> LB -> gorouter -> app

# also works with AAAA records.
app -> external IPv6 address (outside the platform)

# desired scenario 1 - IPv6 all the way
external request over IPv6 -> lb -> gorouter -> app functioning as proxy -> internal app

# desired scenario 2 - IPv6 hairpinning (app makes service broker call to another app)
external request over IPv6 -> lb -> gorouter -> app -> lb -> gorouter -> app

# desired scenario 3 - external IPv6 to platform IPv6 (app makes service broker call to bosh release with gorouter route)
external request over IPv6 -> lb -> gorouter -> app -> lb -> gorouter -> bosh vm
```

Does that help explain the target scenarios? The basic goal/requirement is the ability to handle and properly respond with IPv6 networking, and while being able to address specific AIs with IPv6 isn't necessarily a requirement, it would make it much easier.

> Does an app on CF need to connect to a non-app network destination at an IPv6 address? (That non-app network destination might be the IPv6 address of a platform load-balancer that ultimately proxies to another CF app, but the original network destination of the first TCP hop is IPv6)

Yes, not all of our service brokers are running as AIs, some are bosh releases, so we would need to handle that scenario.

**Comment by mcwumbly** [comment]
Hey @mxplusb, been a while!

We were going through open issues today and spent a bit of time discussing this one. We're going to mark it as `help wanted` to more clearly signify that we don't currently have any plans to do this work given our current resources and priorities.

While we'd welcome contributions from the community here, it's worth noting that in order to meet all of your desired outcomes, this would be a somewhat involved effort. We think it ultimately may touch all of the following components (and their subcomponents) to some degree:

* BOSH
* cf-deployment
* routing-release
* capi-release
* diego-release
* cf-networking-release

Were someone to take it on, it'd be worth putting some design docs together first.  It may be possible to break down this effort into smaller pieces, but that would also take some thought.

Happy to continue discussing here in the meantime...

**Comment by jrussett** [comment]
I'm going to close this as it has been stale for 3 years and because this repo is being archived.

Please see this GitHub issue for why this repo is being archived: https://github.com/cloudfoundry/silk/issues/52
(tl;dr the repo got merged into `silk-release`).

If this feature is still desired and you would like to talk about it, please open up a [new GitHub issue in `silk-release`](https://github.com/cloudfoundry/silk-release/issues/new).
