### ISSUE TITLE
silk-daemon does not poll for policies at startup

### ISSUE THREAD

**Issue by fhambrec** [cloudfoundry/silk#7]
We are currently testing some app to app communication in Cloudfoundry during diego-cell updates. We ran into 'no route to host' and 'timeout 'errors after diego-cells got updated. The errors lasted until the policies were re-polled via the silk-daemon. This means that networking is not able during this timeframe. Reducing the lease_poll_interval_seconds value to 5 seconds solved the problem. However, this fix is not applicable on our larger landscapes. 

The DoCycle method is not called after start or restart of the silk-daemon job on a diego-cell:
https://github.com/cloudfoundry/silk/blob/574bc1a08c28e77aa42ca808659b0fc4be749881/cmd/silk-daemon/main.go#L200

Instead, the job only polls after the interval. A DoCycle at startup of the silk-daemon job could help fixing this issue.

**Comment by fhambrec** [comment]
Short addition:
On the 'Tips for large deployments' documenation it is mentioned that in order to avoid high cpu usage from the silk-daemon one should raise the interval to 300 seconds (5 minutes) which we did for our large landscapes. See this document: https://github.com/cloudfoundry/cf-networking-release/blob/develop/docs/large_deployments.md

**Comment by barakyo** [comment]
hi @fhambrec ,

Would you mind detailing the steps on how to reproduce the errors? This would better help me write acceptance criteria for this feature.

Thanks!

**Comment by fhambrec** [comment]
Hi @barakyo , 
this error should be reproducible by setting up a landscape with 4 diego cells with 2 availability zones. Additionally, 2 apps that communicate with each other should be deployed. Scaling the apps to 2 instances per app will guarantee a reorder of instances during the update of diego cells. With a high lease_poll_interval_seconds value (e.g. 300) applications will run into 'no route to host' and 'timeout' errors after the reorder of an application takes place.

In this Github repository you can find steps on how to set up two exemplary communicating applications: https://github.com/emalm/tls-example-apps

**Comment by barakyo** [comment]
Hi @fhambrec,

Thanks for the update! We've addressed this issue in [this commit](https://github.com/cloudfoundry/silk/commit/a37338e11d1464907536d7262eccb457db2a6649).

We'll keep this issue open until it makes its way through our pipelines.

Thanks!
@barakyo, @KauzClay

**Comment by cameronmoreau** [comment]
Hey @fhambrec 
The update made it through our pipelines and can be found [with this release tag](https://github.com/cloudfoundry/silk-release/tree/2.23.0)
